[api]
    enabled = false
    address = "0.0.0.0:8686"
    playground = true

[log_schema]
    host_key = "host"
    message_key = "message"
    source_type_key = "source_type"
    timestamp_key = "ts"

[sources.http_server]
    type = "http_server"
    address = "0.0.0.0:80"
    encoding = "text"

[sinks.console]
    type = "console"
    inputs = [ "http_server" ]
    encoding.codec = "json"

[transforms.parse_message]
    inputs = ["http_server"]
    type = "remap"
    source = '''
    . = decode_percent(parse_key_value!(.message, field_delimiter: "&"))
    '''

[sinks.loki]
    endpoint = "https://${GF_LOKI_URL}"
    encoding.codec = "json"
    encoding.timestamp_format = "rfc3339"
    inputs = ["parse_message"]
    type = "loki"
    [sinks.loki.labels]
    env = "dev"
